name: Deploy Laravel ke GCP VM

on:
  push:
    branches:
      - main  # Ganti jika branch kamu beda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 34.128.89.144             # Ganti IP VM kamu
        username: averillio_rievan      # Ganti dengan username VM kamu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html/laravel
          git pull origin main
          composer install --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan config:cache
